### ISSUE TITLE
ImportError: No module named 'init_accounts'

### ISSUE THREAD

**Issue by pards** [bigchaindb/bigchaindb-examples#30]
Running on Ubuntu 16.04

`$ docker-compose up`

```
WARNING: The DOCKER_MACHINE_IP variable is not set. Defaulting to a blank string.
Pulling rdb (rethinkdb:latest)...
latest: Pulling from library/rethinkdb
51f5c6a04d83: Pull complete
a44d33f84055: Pull complete
f59a5d313747: Pull complete
005122d30641: Pull complete
0f2b896b867c: Pull complete
Digest: sha256:3ddd16f3fd5457ff715d0f36ac7e84b04a7054372fcda88dd33f914d263e445c
Status: Downloaded newer image for rethinkdb:latest
Creating bigchaindbexamples_rdb_1
Creating bigchaindbexamples_js_1
Creating bigchaindbexamples_bdb_1
Creating bigchaindbexamples_app_1
Creating bigchaindbexamples_ws_1
Attaching to bigchaindbexamples_rdb_1, bigchaindbexamples_js_1, bigchaindbexamples_bdb_1, bigchaindbexamples_app_1, bigchaindbexamples_ws_1
rdb_1  | Recursively removing directory /data/rethinkdb_data/tmp
rdb_1  | Initializing directory /data/rethinkdb_data
rdb_1  | Running rethinkdb 2.3.4~0jessie (GCC 4.9.2)...
rdb_1  | Running on Linux 4.4.0-28-generic x86_64
rdb_1  | Loading data from directory /data/rethinkdb_data
rdb_1  | Listening for intracluster connections on port 29015
rdb_1  | Listening for client driver connections on port 28015
rdb_1  | Listening for administrative HTTP connections on port 8080
rdb_1  | Listening on cluster addresses: 127.0.0.1, 172.18.0.2, ::1, fe80::42:acff:fe12:2%14
rdb_1  | Listening on driver addresses: 127.0.0.1, 172.18.0.2, ::1, fe80::42:acff:fe12:2%14
rdb_1  | Listening on http addresses: 127.0.0.1, 172.18.0.2, ::1, fe80::42:acff:fe12:2%14
rdb_1  | Server ready, "aac47eed5a54_56e" 8ecf6391-657f-4493-a216-cb7f8c186081
js_1   | Demo server running on 0.0.0.0:3000
bdb_1  | INFO:bigchaindb.commands.bigchain:BigchainDB Version 0.5.0
bdb_1  | Traceback (most recent call last):
bdb_1  |   File "/usr/local/bin/bigchaindb", line 9, in <module>
bdb_1  |     load_entry_point('BigchainDB==0.5.0', 'console_scripts', 'bigchaindb')()
bdb_1  |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/commands/bigchain.py", line 306, in main
bdb_1  |     utils.start(parser, globals())
bdb_1  |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/commands/utils.py", line 95, in start
bdb_1  |     func(args)
bdb_1  |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/commands/bigchain.py", line 155, in run_start
bdb_1  |     bigchaindb.config_utils.autoconfigure(filename=args.config, force=True)
bdb_1  |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/config_utils.py", line 228, in autoconfigure
bdb_1  |     newconfig = update(newconfig, file_config(filename=filename))
bdb_1  |   File "/usr/local/lib/python3.5/site-packages/bigchaindb/config_utils.py", line 100, in file_config
bdb_1  |     with open(filename) as f:
bdb_1  | IsADirectoryError: [Errno 21] Is a directory: '/root/.bigchaindb'
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.5/runpy.py", line 184, in _run_module_as_main
app_1  |     "__main__", mod_spec)
app_1  |   File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
app_1  |     exec(code, run_globals)
app_1  |   File "/usr/src/app/server/app.py", line 11, in <module>
app_1  |     from server.lib.api.views import api_views
app_1  |   File "/usr/src/app/server/lib/api/views.py", line 12, in <module>
app_1  |     from init_accounts import get_bigchain
app_1  | ImportError: No module named 'init_accounts'
bigchaindbexamples_bdb_1 exited with code 1
bigchaindbexamples_app_1 exited with code 1
ws_1   | Traceback (most recent call last):
ws_1   |   File "/usr/local/lib/python3.5/runpy.py", line 184, in _run_module_as_main
ws_1   |     "__main__", mod_spec)
ws_1   |   File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
ws_1   |     exec(code, run_globals)
ws_1   |   File "/usr/src/app/server/tornado_app.py", line 10, in <module>
ws_1   |     from init_accounts import get_bigchain
ws_1   | ImportError: No module named 'init_accounts'
bigchaindbexamples_ws_1 exited with code 1
```

`$ docker version`

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

`$ docker-compose version`

```
docker-compose version 1.7.1, build 0a9ab35
docker-py version: 1.8.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
ubuntu@docker-vm:~$ 
```

**Comment by sohkai** [comment]
We've just merged the docker branch for interledger, so you should now be able to start the examples by following [this](https://github.com/bigchaindb/bigchaindb-examples/blob/master/docs/source/interledger.rst). You'll probably have to rebuild your containers first :).
