### ISSUE TITLE
make with docker fails on ubuntu

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb-examples#33]
```
Going to remove bigchaindbexamples_rdb_1
Removing bigchaindbexamples_rdb_1 ... done
docker-compose -f ledgers.yml up -d rdb
WARNING: The DOCKER_MACHINE_IP variable is not set. Defaulting to a blank string.
Creating bigchaindbexamples_rdb_1
docker-compose -f ledgers.yml run --rm bdb-0 bigchaindb -y configure 
WARNING: The DOCKER_MACHINE_IP variable is not set. Defaulting to a blank string.
Generating keypair
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 9, in <module>
    load_entry_point('BigchainDB==0.5.0', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/commands/bigchain.py", line 306, in main
    utils.start(parser, globals())
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/commands/utils.py", line 95, in start
    func(args)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/commands/bigchain.py", line 110, in run_configure
    bigchaindb.config_utils.write_config(conf, config_path)
  File "/usr/local/lib/python3.5/site-packages/bigchaindb/config_utils.py", line 211, in write_config
    with open(filename, 'w') as f:
IsADirectoryError: [Errno 21] Is a directory: '/root/.bigchaindb'
Makefile:8: recipe for target 'configure' failed
make: *** [configure] Error 1
```

**Comment by Braintelligence** [comment]
@diminator I've also got "IsADirectoryError" trying to run BigchainDB in Docker. 

`IsADirectoryError: [Errno 21] Is a directory: '/data/.bigchaindb'`

What should I do? =(

**Comment by diminator** [comment]
@Braintelligence which setup are you using? version of docker, bigchaindb, docker-compose?

**Comment by Braintelligence** [comment]
@diminator I'm very sorry, I think it was my own fault. I missed the brackets in the docker-compose.yml resulting in the volume being merged in a wrong way. I made it work after adding brackets correctly to the volume-specification.
